### ISSUE TITLE
npm i @hugeicons/react 

### ISSUE THREAD

**Issue by sett-hein** [hugeicons/hugeicons#10]
npm error 404 Not Found - GET https://registry.npmjs.org/@hugeicons%2freact - Not found
npm error 404
npm error 404  '@hugeicons/react@^0.5.2' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a

**Comment by ponez** [comment]
Bruh

**Comment by manzik** [comment]
How did you solve it 👉👈

**Comment by ponez** [comment]
By removing it from my project, dead package👍

**Comment by manzik** [comment]
> By removing it from my project, dead package👍

I don't recall asking you

**Comment by sett-hein** [comment]
> > By removing it from my project, dead package👍
> 
> I don't recall asking you

unfortunately ponenz might be right

**Comment by xtawfik** [comment]
Hi there,

We apologize for the inconvenience you’re experiencing. The issue was caused by an invalid npm token. As a quick solution, a new valid token has been added to your account. Please use this token for now.

We’re currently working on launching our private npm registry, which should be available in a few days. This will help eliminate these kinds of issues going forward.

Thank you for using Hugeicons!

Let me know if you’d like any further adjustments!
